version: "3"
services:

  javaapp:
    container_name: app
    build: .
    ports:
      - 8080:8080
    environment:
      HOST: mysql
      DB_NAME: postdb
    restart: always
    depends_on:
      - mysql
      - redis
      - kafka

  javaconsumer:
    container_name: jvconsumer
    build: ../kafka-consumer/.
    ports:
      - 8081:8081
    environment:
      HOST: mysql
      DB_NAME: postdb
    restart: always
    depends_on:
      - mysql
      - kafka

  mysql:
    image: mysql:latest
    container_name: mmsql
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postdb

  redis:
    image: redis:6.2.4
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - 2181:2181
    restart: always

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "request:1:1,csv:1:1"
    restart: always
    depends_on:
      - zookeeper